stages:
  - build
  - test
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build

deploy:
  image: node:latest
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - staging
