export const FETCH_CASES_START_ADMIN = "FETCH_CASES_START_ADMIN";
export const FETCH_CASES_SUCCESS_ADMIN = "FETCH_CASES_SUCCESS_ADMIN";
export const CREATE_CASE_SUCCESS_ADMIN = "CREATE_CASE_SUCCESS_ADMIN";
export const CREATE_CASE_START_ADMIN = "CREATE_CASE_START_ADMIN";
export const ADD_CASE_ADMIN = "ADD_CASE_ADMIN";
export const UPDATE_CASE_ADMIN = "UPDATE_CASE_ADMIN";

export const FETCH_CASE_START_ADMIN = "FETCH_CASE_START_ADMIN";
export const FETCH_CASE_SUCCESS_ADMIN = "FETCH_CASE_SUCCESS_ADMIN";
export const INVITE_PARTY_START_ADMIN = "INVITE_PARTY_START_ADMIN";
export const INVITE_PARTY_SUCCESS_ADMIN = "INVITE_PARTY_SUCCESS_ADMIN";
export const QUIT_CASE_START_ADMIN = "QUIT_CASE_START_ADMIN";
export const QUIT_CASE_SUCCESS_ADMIN = "QUIT_CASE_SUCCESS_ADMIN";
