export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";

export const ADMIN_USER_LIST = "ADMIN_USER_LIST";
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS";
