export const FETCH_CASE_START = 'FETCH_CASE_START'
export const FETCH_CASE_SUCCESS = 'FETCH_CASE_SUCCESS'
export const INVITE_PARTY_START = 'INVITE_PARTY_START'
export const INVITE_PARTY_SUCCESS = 'INVITE_PARTY_SUCCESS'
export const QUIT_CASE_START = 'QUIT_CASE_START'
export const QUIT_CASE_SUCCESS = 'QUIT_CASE_SUCCESS'

