export const FETCH_CASE_TYPES = 'FETCH_CASE_TYPES';
export const FETCH_CASE_TYPE = 'FETCH_CASE_TYPE';
export const CREATE_CASE_TYPE = 'CREATE_CASE_TYPE';
export const UPDATE_CASE_TYPE = 'UPDATE_CASE_TYPE';
export const DELETE_CASE_TYPE = 'DELETE_CASE_TYPE';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
