export const FETCH_CASE_START = "FETCH_CASE_START"
export const FETCH_CASE_SUCCESS = "FETCH_CASE_SUCCESS"
export const INVITE_PARTY_START = "INVITE_PARTY_START"
export const INVITE_PARTY_SUCCESS = "INVITE_PARTY_SUCCESS"
