export const FETCH_CASES_START = "FETCH_CASES_START";
export const FETCH_CASES_SUCCESS = "FETCH_CASES_SUCCESS";
export const CREATE_CASE_SUCCESS = "CREATE_CASE_SUCCESS";
export const CREATE_CASE_START = "CREATE_CASE_START";
export const ADD_CASE = "ADD_CASE";