export const FETCH_CASES_START = "FETCH_CASES_START";
export const FETCH_CASES_SUCCESS = "FETCH_CASES_SUCCESS";
export const CREATE_CASE_SUCCESS = "CREATE_CASE_SUCCESS";
export const CREATE_CASE_START = "CREATE_CASE_START";
export const RESPOND_INVITE_START = "RESPOND_INVITE_START";