export const FETCH_HEARINGS = 'FETCH_HEARINGS';
export const FETCH_HEARING = 'FETCH_HEARING';
export const CREATE_HEARING = 'CREATE_HEARING';
export const UPDATE_HEARING = 'UPDATE_HEARING';
export const DELETE_HEARING = 'DELETE_HEARING';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
