export const UPDATE_ORGANIZATION_START = "UPDATE_ORGANIZATION_START";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const FETCH_ORGANIZATION_START = "FETCH_ORGANIZATION_START";
export const FETCH_ORGANIZATION_SUCCESS = "FETCH_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_START = "DELETE_ORGANIZATION_START";
export const LEAVE_ORGANIZATION_START = "LEAVE_ORGANIZATION_START";
export const LEAVE_ORGANIZATION_SUCCESS = "LEAVE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const ADD_MEMBER_START = "ADD_MEMBER_START";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const REMOVE_MEMBER_START = "REMOVE_MEMBER_START";
export const REMOVE_MEMBER_SUCCESS = "REMOVE_MEMBER_SUCCESS";
export const CREATE_ORGANIZATION_CASE_SUCCESS =
  "CREATE_ORGANIZATION_CASE_SUCCESS";
export const CREATE_ORGANIZATION_CASE_START = "CREATE_ORGANIZATION_CASE_START";
