export const FETCH_ORGANIZATIONS_START = "FETCH_ORGANIZATIONS_START";
export const FETCH_ORGANIZATIONS_SUCCESS = "FETCH_ORGANIZATIONS_SUCCESS";
export const CREATE_ORGANIZATION_START = "CREATE_ORGANIZATION_START";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_START = "DELETE_ORGANIZATION_START";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const RESPOND_INVITE_START = "RESPOND_INVITE_START";
export const RESPOND_INVITE_SUCCESS = "RESPOND_INVITE_SUCCESS";
