export const FETCH_USER_SATRT = "FETCH_USER_SATRT";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USERS_SATRT = "FETCH_USERS_SATRT";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
